### ISSUE TITLE
invoke_popen RuntimeError

### ISSUE THREAD

**Issue by NickStees** [nmeans/phantomherd#1]
I should mention I am on windows, as that is constantly an issue :) But this is what I get when I run the following

C:\phantomcss->phantomherd -s 1 -c 1 casperjs-stress.js
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:1196:in `invoke_popen': no popen: No err
or (RuntimeError)
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:1196:in `popen'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.9.1/lib/em/processes.rb:119:in `system'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/em-synchrony-1.0.6/lib/em-synchrony.rb:130:in `system'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/phantomherd-0.0.1/lib/phantomherd/runner.rb:22:in `block (2 levels)
in run'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/em-synchrony-1.0.6/lib/em-synchrony/fiber_iterator.rb:10:in `call'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/em-synchrony-1.0.6/lib/em-synchrony/fiber_iterator.rb:10:in `block (
2 levels) in each'

**Comment by ReleaseOnMonday** [comment]
Any resolution for this, i am using ruby 2.3.0
